CREATE TABLE "SKILLS" (
    "Id" RAW(16) NOT NULL,
    "Nome" NVARCHAR2(100) NOT NULL,
    "Descricao" NVARCHAR2(500),
    CONSTRAINT "PK_SKILLS" PRIMARY KEY ("Id")
);

CREATE TABLE "USUARIOS" (
    "ID" RAW(16) NOT NULL,
    "NOME" NVARCHAR2(150) NOT NULL,
    "EMAIL" NVARCHAR2(150) NOT NULL,
    "CARGO_ATUAL" NVARCHAR2(100) NOT NULL,
    "CARGO_DESEJADO" NVARCHAR2(100) NOT NULL,
    CONSTRAINT "PK_USUARIOS" PRIMARY KEY ("ID")
);

CREATE TABLE "CURSOS" (
    "Id" RAW(16) NOT NULL,
    "Titulo" NVARCHAR2(150) NOT NULL,
    "Descricao" NVARCHAR2(1000),
    "Provedor" NVARCHAR2(100),
    "CargaHoraria" NUMBER(10) NOT NULL,
    "SkillId" RAW(16) NOT NULL,
    CONSTRAINT "PK_CURSOS" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CURSOS_SKILLS_SkillId" FOREIGN KEY ("SkillId") 
        REFERENCES "SKILLS" ("Id") ON DELETE CASCADE
);

CREATE TABLE "USUARIOS_CURSOS" (
    "CursosAtivosId" RAW(16) NOT NULL,
    "UsuariosMatriculadosId" RAW(16) NOT NULL,
    CONSTRAINT "PK_USUARIOS_CURSOS" PRIMARY KEY ("CursosAtivosId", "UsuariosMatriculadosId"),
    CONSTRAINT "FK_UC_CURSOS" FOREIGN KEY ("CursosAtivosId") 
        REFERENCES "CURSOS" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UC_USUARIOS" FOREIGN KEY ("UsuariosMatriculadosId") 
        REFERENCES "USUARIOS" ("ID") ON DELETE CASCADE
);
